apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: apttm
spec:
  clusterIP: None  # 类型为：Headless Service
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379