apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: apttm
data:
  REDIS_MASTER_HOST: "redis-0.redis" # redis-0是Pod名称，redis是 headless service的名称。 为啥是这个格式，见下面解释：
  REDIS_MASTER_PORT: "6379"

# 如果您的 Pod 名字是 redis-0，并且使用 Kubernetes 中的 StatefulSet 进行部署，那么对应的主机名（host）仍然应该是 redis-0.redis 而不是 redis-0，因为 Kubernetes 会根据 StatefulSet 的规则为每个 Pod 生成 DNS 名称。
# 在 Kubernetes 中，StatefulSet 会为每个 Pod 创建一个基于名称的 DNS 域名，并且采用以下格式：
# 格式： <statefulset-name>-<pod-index>.<headless-service-name>
# 解释：redis-0是Pod名称，redis是 headless service的名称。