--- # 主节点 service
apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  namespace: apttm
spec:
  clusterIP: None  # Headless service，允许每个 Pod 具有稳定的 DNS 名称
  selector:
    app: mysql-master
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
--- # 从节点 service
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  namespace: apttm
spec:
  clusterIP: None  # Headless service，允许每个 Pod 具有稳定的 DNS 名称
  selector:
    app: mysql-slave
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
