# PersistentVolume yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: apttm
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/mysql/data
  storageClassName: mysql-storage-class
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-slave-pv
  namespace: apttm
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/mysql-slave/data
  storageClassName: mysql-storage-class