apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: apttm
data:
  my.cnf: |
    [mysqld]
    server-id = 1
    bind-address = 0.0.0.0 # 允许从节点连接
    # log-bin = mysql-bin # 二进制文件启动，可能一开始无法创建文件，可以一开始注释掉，先动起mysql，之后再修改过来。
    # binlog-do-db = test_db # 指定特定数据库记录