--- # 主节点：
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-master
  namespace: apttm
spec:
  serviceName: "mysql-master"
  replicas: 1
  selector:
    matchLabels:
      app: mysql-master
  template:
    metadata:
      labels:
        app: mysql-master
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_REPLICA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_REPLICA_PASSWORD
          volumeMounts:
            - name: mysql-config-volume
              mountPath: /etc/mysql/my.cnf
              subPath: my.cnf
            - name: mysql-data
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
      volumes:
        - name: mysql-config-volume
          configMap:
            name: mysql-config
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-master-pvc  # 引用现有的 PVC
--- # 从节点
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-slave
  namespace: apttm
spec:
  serviceName: "mysql-slave"
  replicas: 1
  selector:
    matchLabels:
      app: mysql-slave
  template:
    metadata:
      labels:
        app: mysql-slave
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_REPLICA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_REPLICA_PASSWORD
          volumeMounts:
            - name: mysql-config-volume
              mountPath: /etc/mysql/my.cnf
              subPath: my.cnf
            - name: mysql-data
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
      volumes:
        - name: mysql-config-volume
          configMap:
            name: mysql-config
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-slave-pvc  # 引用现有的 PVC
