# 存储密码
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: apttm
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MDgxOAo=
  MYSQL_REPLICA_PASSWORD: MDgxOAo=
# 通过以下命令生成 base64 编码的密码： `echo -n 'yourpassword' | base64`
#  MYSQL_ROOT_PASSWORD: <your-base64-encoded-root-password>